import type { EmptyStateGuideCard, GuideStep } from "./guidance";

export const GUIDE_TOUR_STEPS: GuideStep[] = [
  {
    id: "player-main-characters",
    tourId: "main-player",
    title: "Character list",
    body: "Use this list to switch between your characters. Select one to open details.",
    target: "campaign-characters",
    page: "main",
    allowedRoles: ["player"],
    requiredPermission: "viewCharacter",
    placement: "right",
  },
  {
    id: "player-main-create",
    tourId: "main-player",
    title: "Create character",
    body: "Start a new PC from this button. The wizard follows campaign rules.",
    target: "create-character",
    page: "main",
    allowedRoles: ["player"],
    requiredPermission: "createCharacter",
    placement: "bottom",
  },
  {
    id: "player-main-sheet",
    tourId: "main-player",
    title: "Character details",
    body: "Select a character to review it. Editors can update sections from this panel.",
    target: "character-viewer",
    page: "main",
    allowedRoles: ["player"],
    requiredPermission: "viewCharacter",
    placement: "right",
  },
  {
    id: "player-main-export",
    tourId: "main-player",
    title: "Roll20 export",
    body: "Copy this payload when the sheet is ready. Paste it in Roll20 chat.",
    target: "export-roll20",
    page: "main",
    allowedRoles: ["player"],
    requiredPermission: "exportRoll20",
    placement: "top",
  },
  {
    id: "player-main-display",
    tourId: "main-player",
    title: "Display options",
    body: "Adjust theme and readability here. Changes apply immediately.",
    target: "display-settings",
    page: "main",
    allowedRoles: ["player"],
    requiredPermission: "openDisplay",
    placement: "bottom",
  },
  {
    id: "gm-main-campaign",
    tourId: "main-gm",
    title: "Campaign settings",
    body: "Open campaign rules and options here. Save changes to update everyone.",
    target: "campaign-settings",
    page: "main",
    allowedRoles: ["gm"],
    requiredPermission: "editCampaign",
    placement: "bottom",
  },
  {
    id: "gm-main-access",
    tourId: "main-gm",
    title: "Player access",
    body: "Manage campaign membership here. Add players before assigning character access.",
    target: "invite-users",
    page: "main",
    allowedRoles: ["gm"],
    requiredPermission: "manageCampaignAccess",
    placement: "bottom",
  },
  {
    id: "gm-main-characters",
    tourId: "main-gm",
    title: "Character roster",
    body: "Review campaign characters in this list. Open one to edit or level up.",
    target: "campaign-characters",
    page: "main",
    allowedRoles: ["gm"],
    requiredPermission: "viewCharacter",
    placement: "right",
  },
  {
    id: "gm-main-create",
    tourId: "main-gm",
    title: "Create character",
    body: "Create PCs or NPCs from here. Use this for quick encounter prep.",
    target: "create-character",
    page: "main",
    allowedRoles: ["gm"],
    requiredPermission: "createCharacter",
    placement: "bottom",
  },
  {
    id: "gm-main-export",
    tourId: "main-gm",
    title: "Roll20 export",
    body: "Export selected sheets for table use. Validate values before sharing.",
    target: "export-roll20",
    page: "main",
    allowedRoles: ["gm"],
    requiredPermission: "exportRoll20",
    placement: "top",
  },
  {
    id: "admin-main-new",
    tourId: "main-admin",
    title: "New campaign",
    body: "Create a fresh campaign here. This is best for new rulesets.",
    target: "create-campaign",
    page: "main",
    allowedRoles: ["admin"],
    requiredPermission: "createCampaign",
    placement: "bottom",
  },
  {
    id: "admin-main-campaign",
    tourId: "main-admin",
    title: "Campaign settings",
    body: "Edit campaign content from this button. Publish only after checking data.",
    target: "campaign-settings",
    page: "main",
    allowedRoles: ["admin"],
    requiredPermission: "editCampaign",
    placement: "bottom",
  },
  {
    id: "admin-main-access",
    tourId: "main-admin",
    title: "Access control",
    body: "Manage users, roles, and assignments here. Use this before onboarding players.",
    target: "invite-users",
    page: "main",
    allowedRoles: ["admin"],
    requiredPermission: "manageCampaignAccess",
    placement: "bottom",
  },
  {
    id: "admin-main-create",
    tourId: "main-admin",
    title: "Create character",
    body: "Create characters for testing or demos. You can use PC and NPC types.",
    target: "create-character",
    page: "main",
    allowedRoles: ["admin"],
    requiredPermission: "createCharacter",
    placement: "bottom",
  },
];

export const EMPTY_STATE_GUIDE_CARDS: EmptyStateGuideCard[] = [
  {
    id: "main-no-characters",
    page: "main",
    title: "No characters yet",
    body: "Create your first character to start building. You can return and edit it anytime.",
    primaryLabel: "Create character",
    dismissLabel: "Dismiss",
    allowedRoles: ["player", "gm", "admin"],
    requiredPermission: "createCharacter",
  },
  {
    id: "main-no-campaigns",
    page: "main",
    title: "No campaigns yet",
    body: "Create a campaign before adding characters. Set rules first for clean setup.",
    primaryLabel: "Create campaign",
    dismissLabel: "Dismiss",
    allowedRoles: ["gm", "admin"],
    requiredPermission: "createCampaign",
  },
];
